!======================================================================!
!
!
!	FOURI2 SUBROUTINE: FITS SINGLE COS CURVE TO DATA IN XDATA
!	  = GENERAL FOURIE SUBN WITH PHASE CONVERTED TO DAYS ASSUMING 12
!	    MONTHLY VALUES INPUT (FOR USE WITH ESTMO)
!	J.S. AUBURN     2 JUNE 1988
!	ADAPTED FROM RICHARDSON'S (IN PAR/WGEN); CHANGED SO THAT:
!		A) ONLY ONE CURVE IS FIT, RATHER THAN TRIPLICATE
!		B) AMPLITUDE CALCULATION: C=SQRT(A*A+B*B) IN PLACE OF:
!			C=A/COS(T)  (A LITTLE BETTER)
!		C) PHASE: T=ATAN2(-B,A) IN PLACE OF T=ATAN(-B/A) SO PHASE
!			IS CORRECT IN ALL QUADRANTS
!		D) NPTS IS VARIABLE RATHER THAN FIXED AT 13 (PERIOD IS
!			FIXED AT NPTS)
!
	SUBROUTINE FOURI2_WG (NPTS, XDATA, XBAR, C, T)
!
!	NPTS = NUMBER OF POINTS (INPUT)
!	XDATA = POINTS, EQUALLY SPACED (INPUT)
!	XBAR = MEAN (OUTPUT)
!	C = AMPLITUDE (OUTPUT)
!	T = PHASE, IN DAYS (OUTPUT); ASSUMES 12 POINTS, 1ST POINT = JAN 15
!
	REAL S,XBAR,SUMA,SUMB,XK,A,B,T,C
	REAL XDATA(NPTS)
real*8 :: eps
        EPS = 1.0d-44 !????OK
	S=0.
	DO 10, I = 1, NPTS
	   S=S+XDATA(I)
10      CONTINUE
	XBAR=S/NPTS
	SUMA=0.
	SUMB=0.
	DO 15 K=1,NPTS
    	   XK=K
	   SUMA=SUMA+(XDATA(K)-XBAR)*COS(6.2832*XK/NPTS)
	   SUMB=SUMB+(XDATA(K)-XBAR)*SIN(6.2832*XK/NPTS)
 15	CONTINUE
	A=SUMA*(2./NPTS)
	B=SUMB*(2./NPTS)
!----------------------------------------------------------------------!
!  Bug fix for, I think, when all values are the same.
!----------------------------------------------------------------------!
        IF (B .EQ. 0.0) THEN
	  IF (A .EQ. 0.0) A = EPS
	ENDIF
	T=ATAN2(-B,A)
!  CONVERT PHASE TO DAYS FROM RADIANS, ADD 15 SINCE FIRST POINT IS "MID-JANUARY"
	T = (T * 365/6.2832) + 15
	T = - T
	T = AMOD (T,365.0)
	IF (T.LT.0.0) T = 365.0 + T
	C=SQRT(A*A+B*B)
	RETURN
	END
	BLOCK DATA 
	CHARACTER*3 FRUNIT
	CHARACTER*2 PWUNIT
	CHARACTER*1 MXUNIT,MIUNIT
	CHARACTER*11 SRUNIT
	CHARACTER*7 HYUNIT
	CHARACTER*9 WSUNIT
	COMMON /BLK/ FRUNIT,PWUNIT,MXUNIT,MIUNIT,SRUNIT,HYUNIT,WSUNIT
	DATA FRUNIT/'DAY'/,PWUNIT/'MM'/,MXUNIT/'C'/,MIUNIT /'C'/, &
     &  SRUNIT/'MJ/M*M/DAY '/,HYUNIT/'MPa(VP)'/,WSUNIT/'METER/SEC'/
     	END



